### ISSUE TITLE
前台—账户中心—账户中心—账户提现选择银行卡报错

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#102]
![image](https://cloud.githubusercontent.com/assets/10395446/5628025/444f880e-95dc-11e4-830e-64efef3e490e.png)

**Comment by colinsun3** [comment]
无法重现

**Comment by colinsun3** [comment]
需要先完成实名认证，否则会报错，流程上要优化

**Comment by colinsun3** [comment]
待下期流程优化彻底解决
