### ISSUE TITLE
后台—借款信息—协议编号作为筛选条件,存在相同的协议编号

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#114]
登录后台—>借款信息,协议编号作为筛选条件
预期结果：协议编号是唯一的
实际结果：存在相同的协议编号

![image](https://cloud.githubusercontent.com/assets/10395446/5644080/b2771946-969a-11e4-9e68-caea934fbcbc.png)

**Comment by colinsun3** [comment]
@huyingjlfex
