### ISSUE TITLE
前台—账户中心—个人信息—证件号码为护照时,提示错误

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#119]
![image](https://cloud.githubusercontent.com/assets/10395446/5658789/e532df16-9742-11e4-8ae5-f49fabb77a2b.png)

**Comment by colinsun3** [comment]
@huyingjlfex ,已经解决

**Comment by huyingjlfex** [comment]
@colinsun3  没有解决 ，选择类型为护照时，提示的是：请正确输入您的身份证号码
预期结果：请正确输入证件号码；（个人认为护照时，提示身份证号码 提示不友好）
