### ISSUE TITLE
前台—账户中心—资金管理—当客户提现时,后台处理提现失败,但客户手续费被扣除了

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#136]
1.客户前台登录—账户中心—资金管理
2.如客户账户有100元，点击“提现”
3.后台登录—资金管理—提现处理
4.后台人员将提现手动处理为失败

预期结果：客户账户还有100金额
实际结果：客户账户提现失败，还扣除了3元手续费，现金账户只有97元。

已跟王莹莹沟通过，具体怎么处理还需再讨论

**Comment by colinsun3** [comment]
@huyingjlfex ,经确认，需要扣手续费

**Comment by yoyohermes** [comment]
需求说明：无论是提现成功还是提现失败，均扣除提现手续费
