### ISSUE TITLE
后台—系统管理—参数设置,在后台“还款方式”与前台发布借款“放款方式”没有关联

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#155]
![image](https://cloud.githubusercontent.com/assets/10395446/5733205/3cf77360-9bda-11e4-88e0-e2278ca3c41b.png)
![image](https://cloud.githubusercontent.com/assets/10395446/5733210/552257b6-9bda-11e4-8dcb-14c474658cd2.png)

**Comment by colinsun3** [comment]
@huyingjlfex ,后台已取消还款配置项
