### ISSUE TITLE
后台—系统管理—参数设置,在后台借款用途被禁用后,前台还能展现

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#156]
![image](https://cloud.githubusercontent.com/assets/10395446/5733335/84b1d2b6-9bdc-11e4-83cb-1a1e36a24763.png)
![image](https://cloud.githubusercontent.com/assets/10395446/5733342/8f42d4e6-9bdc-11e4-8050-d6da2be9e66f.png)

预期结果：后台借款用途被禁用后,前台不能展现
实际结果：后台借款用途被禁用后,前台还能展现

**Comment by yoyohermes** [comment]
需求描述：
此问题包含2个事情：
一、后台参数初始化：目前系统需初始化4个参数类“还款方式、产品用途、担保方式、招标时间”。目前这四个参数类均在后台-产品管理-新增产品用到。 
还款方式、产品用途（在前台-我要借款界面显示“借款用途”）：在前台-我要借款界面展示；
担保方式、招标时间：在普通标的详情页展示（担保方式直接展示，招标时间通过"剩余时间"展示）；

二、参数值状态：启用和禁用。 启用时才能显示和被选择；禁用时不展示。

**Comment by lishunfeng** [comment]
开发目前状态：
后台参数初始化中，参数类已支持产品用途，担保方式，产品招标期限（招标时间），由于目前系统仅支持等额本息的计算，所以还款方式暂不支持。

**Comment by huyingjlfex** [comment]
@colinsun3  后台新增了 产品用途，但前台没展现新增的产品用途

**Comment by huyingjlfex** [comment]
后台设置 金额：如果以100递增的话，  金额范围不能低于100
否则 样式有问题
