### ISSUE TITLE
前台—我的账户—个人信息,可用账户金额不正确

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#160]
客户原账户可用金额：999000元；平台放款给这个客户：1000元；除去 100元借款手续费，200风险金管理费；这个客户现账户应该是：999000+700
放款前账户金额：
![image](https://cloud.githubusercontent.com/assets/10395446/5735189/1528d842-9bfd-11e4-95db-7ca687f9be8c.png)
放款后账户金额：
![image](https://cloud.githubusercontent.com/assets/10395446/5735194/1d6f5b02-9bfd-11e4-8e94-c8cc23556245.png)

**Comment by colinsun3** [comment]
@huyingjlfex  ，误操作引起

**Comment by huyingjlfex** [comment]
@colinsun3  误操作充值了
