### ISSUE TITLE
后台—系统管理—参数设置,参数类型里“借款用途”和"产品用途"一个含义

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#161]
![image](https://cloud.githubusercontent.com/assets/10395446/5735277/7a79c3e0-9bfe-11e4-84aa-8b30dc3b633f.png)
需要跟确认产品经理，“借款用途”和"产品用途"同一个含义
 
![image](https://cloud.githubusercontent.com/assets/10395446/5735303/e6219370-9bfe-11e4-8f2a-1a18c2141472.png)
![image](https://cloud.githubusercontent.com/assets/10395446/5735305/f26c8ba8-9bfe-11e4-8b73-c5f688f85290.png)

**Comment by colinsun3** [comment]
一个是定制产品用的，一个是配置债权用的
