### ISSUE TITLE
前台—首页—首页进度条和百分比错误

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#162]
![image](https://cloud.githubusercontent.com/assets/10395446/5735635/151e4c18-9c04-11e4-9741-5a971dae2747.png)

**Comment by yanLeiOfJL** [comment]
@huyingjlfex   请验证

**Comment by colinsun3** [comment]
@huyingjlfex ,已经解决

**Comment by huyingjlfex** [comment]
@colinsun3  我要理财的进度条没有改
