### ISSUE TITLE
后台—菜单—左侧菜单界面设置不正确

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#181]
![image](https://cloud.githubusercontent.com/assets/10395446/5771317/579d7f9c-9d75-11e4-982f-ad2b0b1f9edc.png)

**Comment by huyingjlfex** [comment]
@colinsun3 没解决

**Comment by colinsun3** [comment]
@huyingjlfex ,已按照文档修改

**Comment by huyingjlfex** [comment]
![image](https://cloud.githubusercontent.com/assets/10395446/5849306/cb633ee6-a21e-11e4-9171-1ef1ba22088f.png)
