### ISSUE TITLE
后台—资金管理—风险金账户,风险金没有转入和转出用户

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#184]
![image](https://cloud.githubusercontent.com/assets/10395446/5771990/5cbb4f54-9d84-11e4-9430-fc0ac6f8f5ee.png)

**Comment by colinsun3** [comment]
@huyingjlfex ，转给用户下期再议

**Comment by yoyohermes** [comment]
@huyingjlfex ，请解释下没有转入和转出给用户具体指啥？是说记了流水，实际对于用户可用余额没有做加法减法？还是说这里没有展示当前资金出入金给某个用户对象？

**Comment by huyingjlfex** [comment]
@yoyohermes 需要显示资金转入的对象

**Comment by yoyohermes** [comment]
需求说明：
此处存有2个问题：
1）优化问题：在平台相关账户资金流水查看时，在“转出”与“备注”之间新增易联，列头为“对象”；
     对象：取值当前资金流水关联的用户信息，显示“用户昵称”；
     备注：取值当前资金流水关联的业务信息，显示“标的名称及编号”
2）数据展示bug：
     此处只以“平台风险金”的立场查看流水，即只展示相对于平台风险金账户的出金与入金记录。

举例：借款人张三借款100元，风险金账户收取借款金额的2%，则满标放款时，关于风险金的流水：
i. 张三将风险金转账至平台风险金账户：张三可用余额减少2元，平台风险金账户余额增加2元；

查看风险金账户资金流水：
时间                                转入             转出          对象                              备注
2015.2.4 11:23:43         2.00                               张三的昵称                   资金周转（201507040003）
