### ISSUE TITLE
前台—账户中心—资金管理—客户充值后,资金明细没有充值手续费流水

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#185]
客户充值后,资金明细有现金账户充值，但没有充值手续费流水
![image](https://cloud.githubusercontent.com/assets/10395446/5772815/a67856a0-9d93-11e4-9877-c301b34f443d.png)

**Comment by huyingjlfex** [comment]
@colinsun3  资金明细里没有手续费流水记录

**Comment by yoyohermes** [comment]
需求说明：
目前历史实现机制是：用户充值至平台账户，平台账户将充值金额支出至用户现金账户，同时平台账户支出充值手续费。

关于充值资金流水优化，下期将根据用户需求接入三方支付时一起考虑
