### ISSUE TITLE
后台—债权管理—导入债权的查看明细里的还款计划里已还款期数不对

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#216]
![image](https://cloud.githubusercontent.com/assets/10395446/5798115/3e87a816-9fff-11e4-8a16-014399fdcb5c.png)

导入进来的剩余金额是：600，说明第一期已经还款过了
2015-1-1日默认是还款了，列表中“还款”按钮是不可操作的，实际可操作，债权人要多划扣一期的钱

**Comment by yanLeiOfJL** [comment]
h已解决
