### ISSUE TITLE
前台—注册—注册用户激活邮件信息内容不正确,发送邮件人没有配置

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#268]
![image](https://cloud.githubusercontent.com/assets/10395446/5831986/12b423fc-a178-11e4-9e85-d28ea2ad1870.png

**Comment by colinsun3** [comment]
@huyingjlfex ，配置页面已经取消此项配置

**Comment by huyingjlfex** [comment]
@colinsun3  哦
