### ISSUE TITLE
后台产品管理-新增产品：期限和年利率老提示错误，无法提交

### ISSUE THREAD

**Issue by yoyohermes** [jlfex/hermes#279]
![image](https://cloud.githubusercontent.com/assets/10193528/5833254/1ff27960-a18c-11e4-8a59-90f0cb90ea2f.png)

**Comment by huyingjlfex** [comment]
@colinsun3  把期限“天”屏蔽掉，第二期做

**Comment by huyingjlfex** [comment]
增加管理费

**Comment by huyingjlfex** [comment]
第二期数据库初始化，三期后台页面增加
