### ISSUE TITLE
前台—我的账户—非普通标的剩余时间不正确

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#296]
![image](https://cloud.githubusercontent.com/assets/10395446/5851471/c2cedd70-a242-11e4-9e5d-f3dfc89b4753.png)

**Comment by huyingjlfex** [comment]
@colinsun3  剩余时间改对了，剩余期限原本好的，改坏了

**Comment by yoyohermes** [comment]
需求说明：
债权转让标 投标详情页：
剩余期限： 取值为 后台发售时 系统计算出来的 ”剩余期限“【计算规则：剩余期限=债权到期日-招标结束日期】；
剩余时间：是指当前时间离”招标结束日期“的倒计时。【计算规则：剩余时间=”招标结束日期“-当前时间点】；
