### ISSUE TITLE
后台—债权管理—债权期限展示数据不正确

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#307]
![image](https://cloud.githubusercontent.com/assets/10395446/5854126/795003ea-a265-11e4-9204-3983c1fc6bba.png)

债权导入、债权发售、已转让债权 期限不正确

**Comment by yoyohermes** [comment]
需求描述：外部债权 包含2个期限值：原始债权期限、剩余期限
1.原始债权期限：是指原始标的的借款期限（即导入excel时sheet1的“借款期限”），
2.剩余期限：一个是外部债权导入成功后（包含sheet1和sheet2数据均成功），显示在“债权发售”列表界面，状态为“待发售“，未进行发售前”剩余期限“无值，进行发售后”剩余期限“即为发售时根据”招标结束日期“计算出来的”剩余期限“。 
【注：发售至前台（状态为”招标中“) ，招标期结束时未满标的外部债权状态更新为”待发售“，可以再次发售，直至过了”债权结束日“】


此期期望达到的效果：
1.债权导入 和 债权发售列表：列表中”期限“显示 ”原始债权期限“；
2.已转让债权列表：列表中”期限“ 显示 ”剩余期限“
