### ISSUE TITLE
前台—首页—非普通标展示数据不正确

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#308]
![image](https://cloud.githubusercontent.com/assets/10395446/5854304/54c8c91a-a267-11e4-963d-02ee8f893d80.png)

**Comment by yoyohermes** [comment]
需求描述： 前台 债权转让区，期限：取值为 当前标的后台发售时 的”剩余期限“【此剩余期限根据发售时的”招标结束日期“计算】
