### ISSUE TITLE
后台—债权管理—债权导入中“债权信息”,债权剩余期限天数无

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#313]
![image](https://cloud.githubusercontent.com/assets/10395446/5855860/e0b49534-a277-11e4-98f6-7f25186b5599.png)

**Comment by yoyohermes** [comment]
需求描述：此期不处理，下期优化

**Comment by yoyohermes** [comment]
需求说明：此问题建议关闭，与#379合并处理
