### ISSUE TITLE
前台—首页—我的公司没有链接内容

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#321]

**Comment by yoyohermes** [comment]
需求描述：这个本期先拿掉，不做展示。

**Comment by yoyohermes** [comment]
需求说明：
hermes前台：foot区域展示“公司介绍”；
1）公司介绍包含的菜单（如平台原理等）可通过后台-内容管理-分类管理维护；
2）公司介绍与“帮助中心”一样，在后台-内容管理-分类管理 系统初始化成一级分类；
![image](https://cloud.githubusercontent.com/assets/10193528/5991359/5e263f46-aa24-11e4-8352-a5b8f95a795a.png)
