### ISSUE TITLE
普通标：支持提前还款、逾期还款

### ISSUE THREAD

**Issue by yoyohermes** [jlfex/hermes#349]
备注：债权转让标，只支持正常还款，不考虑提前还款和逾期还款

**Comment by yoyohermes** [comment]
逾期还款需求说明：
1.每日定时跑批（暂定为凌晨02:00，可修改跑批时间），检查所有计划还款日期为“前一日”且状态为“未还款”的还款记录；
2.系统对“未还款”的还款记录进行自动还款：
   检查借款人的可用余额是否>=当期应还总额，
     i.若是，则系统自动还款，并将当前还款记录的还款状态更新为“已还款”；
    ii.若不是则3.
3.系统将“未还款”的还款记录状态更新为“已逾期”，计算并保存逾期天数、逾期罚息，更新还款计划表；
4.每日执行定时跑批任务，并更新还款状态、逾期天数、逾期罚息、应还总额等。

**Comment by huyingjlfex** [comment]
@yanLeiOfJL @yoyohermes  如果 6-1；7-1；8-1三期逾期了，到8-2号跑自动还款job时，账户金额足够还三期的钱；目前程序只还6-1号逾期的；请确认 8-2号自动还三期的，还是只还6-1期的逾期金额
