### ISSUE TITLE
公告管理：可以新增N条公告 。

### ISSUE THREAD

**Issue by yoyohermes** [jlfex/hermes#356]
一、后台-内容管理-公告管理：支持多条公告管理（包含增删改查）。
二、前台-首页-公告：
1）首页最多可以展示5条公告，且左右滚动显示；
2）点击“更多”，查看公告列表界面；
3）查看公告详情。

**Comment by huyingjlfex** [comment]
@lishunfeng  @yoyohermes  
公告前台展示，刚刚跟顺锋了解了下情况，现在因首页展示多条左右滚动暂时还未实现 ， 此需求现简化为：首页只展示最新的一条公告，包含日期和时间 
不做多条滚动
点击更多公告，查看公告列表 。 
公告列表界面，点击公告标题，查看公告详情
