### ISSUE TITLE
后台—内容管理—发布内容里上传图片功能不可用

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#370]
![image](https://cloud.githubusercontent.com/assets/10395446/5953807/a6282e56-a7c9-11e4-9a77-bb5e8bef4605.png)

**Comment by yoyohermes** [comment]
需求说明：一期使用的文本编辑器功能虽然很丰富，但是有时加载不出来。为解决此问题，已与顺峰讨论确定此期优化方案如下：
1.找一个较轻量级的文本编辑器，需具备常用功能；
2.确保文本编辑器快速加载，且常用功能好用；

**Comment by huyingjlfex** [comment]
@lishunfeng @yanLeiOfJL  上传gif图片就会报错
