### ISSUE TITLE
前台—我要理财—担保方式不正确

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#372]
![image](https://cloud.githubusercontent.com/assets/10395446/5954249/fd986d08-a7cf-11e4-9e28-bbfb984719dc.png)

预期结果：
![image](https://cloud.githubusercontent.com/assets/10395446/5954268/26fe013a-a7d0-11e4-8f76-b7182b5da32b.png)

**Comment by yoyohermes** [comment]
担保方式取值说明：
1）普通标：担保方式取后台-产品管理-“担保方式”；
2）债权转让标：担保方式取后台-债权转让-债权发售-“担保方式”。

**Comment by huyingjlfex** [comment]
#346
