### ISSUE TITLE
后台-债权转让-债权发售界面：转让价格计算规则优化

### ISSUE THREAD

**Issue by yoyohermes** [jlfex/hermes#374]
后台-债权转让-债权发售时，转让价格计算规则优化：
一期转让价格=剩余本金，现二期优化为：
转让价格=剩余本金+利息；
剩余本金：=上一个还款日正常还款后剩余本金；
利息：=当期应还利息*（当前日期-上一个还款日）/（当期计划还款日期-上一个还款日）；

**Comment by yanLeiOfJL** [comment]
@yoyohermes  需求有疑问

**Comment by huyingjlfex** [comment]
@yanLeiOfJL  未解决
![image](https://cloud.githubusercontent.com/assets/10395446/6054302/4ffe27a8-ad26-11e4-92a2-5d676e980f99.png)
![image](https://cloud.githubusercontent.com/assets/10395446/6054303/540a3ba2-ad26-11e4-973d-f3f14a33f5e7.png)
![image](https://cloud.githubusercontent.com/assets/10395446/6054305/57872ace-ad26-11e4-8ab9-a8a55d1c7bdc.png)
