### ISSUE TITLE
后台-债权转让-各列表定义优化

### ISSUE THREAD

**Issue by yoyohermes** [jlfex/hermes#379]
一、状态优化：
目前外部债权包含“验证失败、待发售、投标中、还款中、已还清、转让失败”状态，现进行优化：
将“转让失败”状态优化为“已过期”；

二、债权导入：
1）列表：查看所有导入成功的外部债权列表，包含“验证失败、待发售、投标中、还款中、已还清、已过期”状态；列表数据需按照原型更新；
![image](https://cloud.githubusercontent.com/assets/10193528/6014144/dcf0747e-ab99-11e4-9467-50571c881a4d.png)

2）查看详情：只包含“基本信息”和“还款及回款计划表”， 只能查看，不能对债权进行任何业务操作；

三、债权发售：
1）列表：查看所有“待发售、投标中”状态的债权，列表数据需按原型更新;
![image](https://cloud.githubusercontent.com/assets/10193528/6014169/3754255a-ab9a-11e4-8673-2d8495af31a9.png)
2)查看详情：包含“基本信息”、“债权信息”和“还款及回款计划表”;
 A、基本信息：可进行充值操作；
 B、债权信息：
       i.剩余本金：当未发售前值取空；当发售后取最新发售转让价格中的“剩余本金”；
       ii.剩余期限：当未发售前值取空；当发售后取最新发售的“剩余期限”；
       历史操作：记录并查看当前外部债权从成功导入、债权发售、满标放款至已转让债权列表的操作人、操作时间等；
       协议：《债权转让协议》模板展示；

四、已转让债权列表：
1）列表：查看“还款中、已还清”状态的债权，列表数据需按原型更新;
![image](https://cloud.githubusercontent.com/assets/10193528/6014230/347260a8-ab9b-11e4-9477-77b2aa8e31a7.png)
2）可查看投标记录；
3）可查看回款详情：可进行还款操作。

**Comment by huyingjlfex** [comment]
@yanLeiOfJL 
问题1： 《债权转让协议》有问题
![Uploading image.png . . .]()

预期《债权转让协议》
![Uploading image.png . . .]()
![Uploading 11.png . . .]()
![Uploading 22.png . . .]()
