### ISSUE TITLE
前台—认证—手机认证的“更换号码”链接不可用

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#478]
![image](https://cloud.githubusercontent.com/assets/10395446/6775285/95675550-d169-11e4-9d38-f95a20197584.png)

**Comment by huyingjlfex** [comment]
![Uploading image.png . . .]()

**Comment by yoyohermes** [comment]
请优化

**Comment by huyingjlfex** [comment]
1. 点击“更换号码”，没有高亮显示输入框
2. 验证码错误 的样式没有优化
