### ISSUE TITLE
前台—认证—实名认证信息没有保存成功

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#479]
步骤：
一个新用户：手机、实名、银行卡都未认证
1. 手机认证时，点击“跳过”
2.实名认证时填写资料，点击“确认”
3.银行认证时，点击“跳过”
4. 用户退出重新登录
预期结果：实名认证已经认证过了不需要再重新认证
实际结果：还需要实名认证

另外：实名认证的名字长度没有控制，是否考虑控制长度

**Comment by yoyohermes** [comment]
关于“另外：实名认证的名字长度没有控制，是否考虑控制长度”的需求说明：
目前暂不考虑。 后期做校验优化：长度及限制
