### ISSUE TITLE
hermes前台-我要理财-投标：点击充值，冲100，成功充值到账户的金额是100*2

### ISSUE THREAD

**Issue by mayunyan** [jlfex/hermes#506]
1.充值方式：中国银联，国付宝，中国工商银行，充值到账户的金额都是双倍的。
![1](https://cloud.githubusercontent.com/assets/11747288/7017954/54e175fa-dd31-11e4-803d-25ce3054626b.png)
![2](https://cloud.githubusercontent.com/assets/11747288/7017957/5da0ab3e-dd31-11e4-8fe7-98c8ac533c8c.png)
![3](https://cloud.githubusercontent.com/assets/11747288/7017959/632c3c94-dd31-11e4-83c7-45a2a52ab784.png)

**Comment by lishunfeng** [comment]
此问题暂时可以不用理会，待开发人员全部开发完成，hermes系统不会再提供充值功能的入口
