### ISSUE TITLE
前台—首页—债权区,jlfex理财产品募集日结束

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#520]
jlfex理财产品募集日结束了，前台还展示吗

**Comment by yoyohermes** [comment]
需求描述：
1.展示；
2.与易联天下对接的债权转让标招标结束时间点为招标结束日（即起息日前一日）的12:00，12：00无论是否满标，前台债权转让区的标的信息展示区，系统自动将操作列的“投标”按钮灰色禁用，剩余金额自动更新为“0.00”，投标进度自动更新为“100%”

**Comment by yoyohermes** [comment]
需求描述：
1.展示；
2.与易联天下对接的债权转让标招标结束时间点为招标结束日（即起息日前一日）的12:00，12：00无论是否满标，前台债权转让区的标的信息展示区，系统自动将操作列的“投标”按钮灰色禁用，剩余金额自动更新为“0.00”，投标进度自动更新为“100%”
