### ISSUE TITLE
前台-我要理财-标的进度条的显示不稳定

### ISSUE THREAD

**Issue by shenhao999** [jlfex/hermes#54]
【操作】Chrome浏览器，反复点击同一个查询条件
【结果】刷新出的表数据，有时显示进度条，有时不显示
![image](https://cloud.githubusercontent.com/assets/10202846/5605069/39d23644-9422-11e4-8865-3129cd6957ca.png)

**Comment by colinsun3** [comment]
@huyingjlfex ,已改变展示方式
