### ISSUE TITLE
hermes前台-账户中心：点击账户提现，新增银行卡 会影响银行卡管理不工作

### ISSUE THREAD

**Issue by mayunyan** [jlfex/hermes#541]
1.认证中心：都已全部认证，银行卡已绑定
2点击账户提现：添加银行卡，添加成功后，账户提现页面出现两张银行
3.点击银行卡管理：银行卡管理页面打不开
4.点击我要理财，对易联债券进行投标，输入金额，点击投标，页面跳转到：请到认证中心进行银行卡绑定 提示页面

**Comment by yanLeiOfJL** [comment]
@huyingjlfex   此处不进行绑卡操作
