### ISSUE TITLE
前台-首页-没有上传过头像的出让人，首页的头像中显示了昵称

### ISSUE THREAD

**Issue by shenhao999** [jlfex/hermes#55]
首页头像
![image](https://cloud.githubusercontent.com/assets/10202846/5605092/1f56f09c-9423-11e4-953d-541d3c5e86ee.png)
对比我要理财页面的头像
![image](https://cloud.githubusercontent.com/assets/10202846/5605105/b9f4f34c-9423-11e4-8e25-ed24e9be8668.png)

**Comment by colinsun3** [comment]
@shenhao999 ,已经解决
