### ISSUE TITLE
系统异常面优化

### ISSUE THREAD

**Issue by yanLeiOfJL** [jlfex/hermes#597]
报错页面提醒：常见错误友好提醒；

**Comment by huyingjlfex** [comment]
400 - 对不起，请求中有语法问题！
403 - 对不起，您的权限不足！
404 - 页面不存在
500 - 系统发生内部错误.

**Comment by lishunfeng** [comment]
模拟404错误：人为修改url地址，比如：点击我要理财，正确的url是http://localhost:8085/invest/index，人为修改为http://localhost:8085/invest/indexaa，点击回车即可出现404错误
模拟500错误：人为修改ftl文件名称，比如：点击生成借款方案，把原来的跳转页面loanprogram.ftl（全路径：webapp/theme/default/loan/loanprograme）名称随意改掉，然后刷新之后再次点击生成借款方案，即可模拟500错误。
403错误暂时没有
