### ISSUE TITLE
用户体验优化

### ISSUE THREAD

**Issue by yanLeiOfJL** [jlfex/hermes#598]
用户体验优化：页面最小高度限制、风格及布局统一、功能选项定位、
  查询体验优化等页面展现及业务流程方面进行用户体验优化

**Comment by huyingjlfex** [comment]
1.登录（不是首页上面的快速登录）
2.注册
3.3种认证时候的页面
4.发送邮件提示成功的页面
5.通过邮箱找回密码的页面
6.首页点击更多公告页面
7.重新发送邮件之后的页面
目前想到的就这几个，测试过程中你多点击试试，可能会有潜在的其他页面
