### ISSUE TITLE
前台-修改密码-字段校验的判断规则及提示方式都需完善

### ISSUE THREAD

**Issue by shenhao999** [jlfex/hermes#61]
1、校验规则与注册不一致
如：新密码输入32位密码，修改成功，与注册规则不一致
2、校验的提示方式需完善
如：
1）新密码、确认密码不一致，没有文字提示
![image](https://cloud.githubusercontent.com/assets/10202846/5605616/f08c8764-943f-11e4-80ba-05958eebeef5.png)
2）提示语的位置
![image](https://cloud.githubusercontent.com/assets/10202846/5605697/92803624-9445-11e4-8a64-755ccee85513.png)

**Comment by colinsun3** [comment]
@shenhao999 ,已经解决
