### ISSUE TITLE
前台-登录页面、首页登录、注册-邮箱字段没有展示常用邮箱后缀

### ISSUE THREAD

**Issue by shenhao999** [jlfex/hermes#62]
以下截自需求文档，且已与产品确认：

输入框支持邮箱后缀提示功能，下拉列表罗列出当前常用邮箱后缀，
包含@sina.com、@163.com、@qq.com、@126.com、@sina.cn、@hotmail.com、@gmail.com、@sohu.com、@139.com、@189.cn，用户可通过上下移动光标选中合适的邮箱后缀。

**Comment by yanLeiOfJL** [comment]
@huyingjlfex  已修复
