### ISSUE TITLE
前台—普通标—自动流标后，处理中的投标状态没有变更，导致用户无法投新标

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#631]
普通标A ,理财人投A标，中金返回结果正在处理中，等A标募集日截止后，A标自动流标。理财人买新的标B时，提示还有处理中的订单，无法投标

hermes_test21

SELECT * FROM hm_loan t WHERE t.loan_no='201504150013';
SELECT * FROM hm_invest t WHERE t.`loan` IN(
  SELECT id FROM hm_loan t WHERE t.loan_no='201504150013'
);
SELECT * FROM hm_order_cfca t WHERE t.`invest_id` IN(
 SELECT id FROM hm_invest t WHERE t.`loan` IN(
  SELECT id FROM hm_loan t WHERE t.loan_no='201504150013'
)
);

**Comment by yanLeiOfJL** [comment]
@huyingjlfex   后续业务流程 分离 改造
