### ISSUE TITLE
后台—参数配置—配置类别：开关管理少了短信失效时间、邮件认证失效时间

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#666]
需求要求：
开关管理：手机认证开关、短信失效时间、邮件认证失效时间

实际结果：少了短信失效时间、邮件认证失效时间
fee.withdraw.switch	    提现手续费类型开关	1	0： 区间模式 1：比例模式
auth.cellphone.switch	    手机认证开关	1	0：开启 1：关闭	
month.manager.fee.switch    月缴管理费类型开关	0	0：比例模式 1：定值模式
auth.realname.switch	    实名认证开关	1	0：开启 1：关闭

**Comment by yanLeiOfJL** [comment]
开关管理：手机认证开关、短信失效时间、邮件认证失效时间 都是有的

**Comment by huyingjlfex** [comment]
短信失效时间：现在划分到“其他类”，不属于“开关管理”类别
邮件认证失效时间：现在划分到“邮件类”，不属于“开关管理”类别
