### ISSUE TITLE
前台—提现—开关类有提现比例模式,费率类里没有提现比例费项

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#678]

**Comment by yanLeiOfJL** [comment]
已添加

**Comment by huyingjlfex** [comment]
fee.withdraw.rate	提现比例率
fee.withdraw.config	提现手续费
这名字重新取规范点

**Comment by huyingjlfex** [comment]
fee.withdraw.rate	提现比例率
fee.withdraw.config	提现手续费
这名字重新取规范点

**Comment by huyingjlfex** [comment]
fee.withdraw.rate	提现比例率
fee.withdraw.config	提现手续费
这名字重新取规范点

**Comment by huyingjlfex** [comment]
把“提现比例率”改为“提现手续费比例率”
把“提现手续费改为“提现手续费固定值”
