### ISSUE TITLE
后台—债权管理—发售时招标结束日期约束有问题

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#689]
当前系统时间：2015-5-13日，选择招标结束日期为：2015-5-14日无法选择

当天(2015-05-13) < 招标结束日期 <当期待还款日期-2T[2015-05-14]

**Comment by yanLeiOfJL** [comment]
由于业务规则限制，还款计划时间为 2015-5-16日，需要等到2015-5-16日之后才能发售。
