### ISSUE TITLE
后台-处理提现，报错

### ISSUE THREAD

**Issue by shenhao999** [jlfex/hermes#73]
![image](https://cloud.githubusercontent.com/assets/10202846/5610545/35951420-94f4-11e4-9ff5-674804823290.png)

**Comment by colinsun3** [comment]
@huyingjlfex ,提供重现方式

**Comment by huyingjlfex** [comment]
如客户账户可用金额：100元
先取100元，会收取3元手续费
提示金额不足;
然后再输入97元，界面就报错了
![image](https://cloud.githubusercontent.com/assets/10395446/5735535/977eef34-9c02-11e4-9e35-be544ff33405.png)

**Comment by colinsun3** [comment]
由银行卡数据错误引起，银行卡长度要4位以上

**Comment by huyingjlfex** [comment]
银行卡没有做校验，等做完校验再关吧 @colinsun3
