### ISSUE TITLE
后台—权限管理—用户被赋予的角色还能编辑

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#799]
admin 给李四用户 赋予了角色名称：“ 李四的角色”，李四登录后，看到李四的角色，可以进行编辑，修改名称
假设这个角色不是 李四一个人用
其他用户王五也公用此角色，
实际结果：被李四给改了
预期结果：不允许变更自己被赋予的角色

**Comment by yanLeiOfJL** [comment]
@huyingjlfex    已经修复。
