### ISSUE TITLE
前台—注册—注册用户激活邮件信息内容不正确

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#87]
![image](https://cloud.githubusercontent.com/assets/10395446/5623594/642c7894-9591-11e4-8b85-2659e746011d.png)

注册用户激活邮件 和 找回密码邮件的 “访问平台名称”、“客服热线”内容不正确

**Comment by colinsun3** [comment]
@shenhao999 ，已替换成无用链接

**Comment by huyingjlfex** [comment]
@colinsun3 ,没有修复
