### ISSUE TITLE
前台—投标—理财人投标金额被限制，导致招标失败

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#89]
借款人发布借款申请，申请金额为：5050元；
投资人投5050元时，被限制要求输入数字应为100的整倍
![image](https://cloud.githubusercontent.com/assets/10395446/5625200/404303f6-95b1-11e4-8efe-8fd735b1778a.png)

**Comment by colinsun3** [comment]
@huyingjlfex  ，数据库参数设置为必须为100的整数倍
