### ISSUE TITLE
前台—账户中心—我的借款—建议借款列表加个编号来识别具体借款单

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#91]
![image](https://cloud.githubusercontent.com/assets/10395446/5625494/e4ee20e8-95b6-11e4-930a-97a4f874303d.png)

**Comment by colinsun3** [comment]
要重新编排页面，暂时不考虑

**Comment by huyingjlfex** [comment]
@yoyohermes @colinsun3  现在是第二期

**Comment by yanLeiOfJL** [comment]
@huyingjlfex  要重新编排页面，暂时不考虑 。
