### ISSUE TITLE
前台—账户中心—认证中心—手机认证发送短信功能不可用

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#94]
前台—账户中心—认证中心，输入手机号，点击“获取验证码”，手机没有收到验证码
![image](https://cloud.githubusercontent.com/assets/10395446/5625683/866e5584-95ba-11e4-8684-fa8a73bf6491.png)

**Comment by colinsun3** [comment]
需要配置短信通道，与具体服务供应商有关

**Comment by colinsun3** [comment]
@huyingjlfex ,已经解决
